name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: cicdtest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set application.yaml from secret
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YAML }}" > ./src/main/resources/application.yaml

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Decode GCP Service Account
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "${{ github.workspace }}/gcp-key.json"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker auth
      run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/${{ env.IMAGE_NAME }} .

    - name: Push Docker image
      run: |
        docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/${{ env.IMAGE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.IMAGE_NAME }} \
          --image=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/${{ env.IMAGE_NAME }} \
          --platform=managed \
          --region=${{ secrets.REGION }} \
          --allow-unauthenticated \
          --port=8080
